/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DecksRouteRouteImport } from './routes/decks/route'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudyRouteImport } from './routes/study'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as DecksIndexRouteImport } from './routes/decks/index'
import { Route as DecksDeckIdRouteImport } from './routes/decks/$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRouteRoute = DecksRouteRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecksRouteRoute,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => DecksRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tags': typeof TagsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tags': typeof TagsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks': typeof DecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRoute
  '/study': typeof StudyRoute
  '/tags': typeof TagsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks'
    | '/activity'
    | '/settings'
    | '/study'
    | '/tags'
    | '/decks/$deckId'
    | '/decks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/settings'
    | '/study'
    | '/tags'
    | '/decks/$deckId'
    | '/decks'
  id:
    | '__root__'
    | '/'
    | '/decks'
    | '/activity'
    | '/settings'
    | '/study'
    | '/tags'
    | '/decks/$deckId'
    | '/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksRouteRoute: typeof DecksRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  SettingsRoute: typeof SettingsRoute
  StudyRoute: typeof StudyRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof DecksRouteRoute
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof DecksRouteRoute
    }
  }
}

interface DecksRouteRouteChildren {
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DecksIndexRoute: typeof DecksIndexRoute
}

const DecksRouteRouteChildren: DecksRouteRouteChildren = {
  DecksDeckIdRoute: DecksDeckIdRoute,
  DecksIndexRoute: DecksIndexRoute,
}

const DecksRouteRouteWithChildren = DecksRouteRoute._addFileChildren(
  DecksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksRouteRoute: DecksRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  SettingsRoute: SettingsRoute,
  StudyRoute: StudyRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
